version: '3.8'

services:
  jenkins-controller:
    image: jenkins/jenkins:lts-jdk17
    container_name: jenkins-controller
    restart: unless-stopped
    ports:
      - "8081:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
    networks:
      - jenkins-network

  jenkins-agent:
    build:
      context: .
      dockerfile: jenkins-agent.Dockerfile
    container_name: jenkins-agent
    restart: unless-stopped
    depends_on:
      - jenkins-controller
    networks:
      - jenkins-network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      TF_TOKEN_app_terraform_io: <your hcp account token here>

volumes:
  jenkins_home:

networks:
  jenkins-network:
    driver: bridge
