version: '3.8'

services:
  jenkins-controller:
    build:
      context: .
      dockerfile: jenkins-controller.Dockerfile
    container_name: jenkins-controller
    restart: unless-stopped
    ports:
      - "8081:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
    networks:
      - jenkins-network

  jenkins-agent:
    build:
      context: .
      dockerfile: aws/storage/efs-ec2-simple/jenkins-agent.Dockerfile
    container_name: jenkins-agent
    restart: unless-stopped
    depends_on:
      - jenkins-controller
    networks:
      - jenkins-network
    volumes:
      - ./aws/storage/efs-ec2-simple:/home/jenkins/agent/aws/storage/efs-ec2-simple

volumes:
  jenkins_home:

networks:
  jenkins-network:
    driver: bridge
