pipeline {
    agent any
    environment {
        REPO_URL = 'https://github.com/esteban1192/infrastructure-examples.git'
        DEPLOYMENTS_DIR = '/home/jenkins/agent/deployments'
        PROJECT_PATH = 'aws/security/waf-sql-injection-protection'
        AWS_ACCESS_KEY_ID     = credentials('AWS_ACCESS_KEY_ID')
        AWS_SECRET_ACCESS_KEY = credentials('AWS_SECRET_ACCESS_KEY')
    }
    stages {
        stage('Clone or Pull Repository') {
            steps {
                sh '''
                    if [ -d "$DEPLOYMENTS_DIR/.git" ]; then
                        echo "Repository exists. Pulling latest changes..."
                        cd $DEPLOYMENTS_DIR
                        git pull origin main
                    else
                        echo "Repository does not exist. Cloning..."
                        mkdir -p $DEPLOYMENTS_DIR
                        git clone $REPO_URL $DEPLOYMENTS_DIR
                    fi
                    ls -l $DEPLOYMENTS_DIR
                '''
            }
        }
        stage('Terraform Init') {
            steps {
                sh '''
                    cd $DEPLOYMENTS_DIR/$PROJECT_PATH
                    terraform --version
                    terraform init
                '''
            }
        }
        stage('Terraform Plan') {
            steps {
                sh '''
                    cd $DEPLOYMENTS_DIR/$PROJECT_PATH
                    terraform plan -out=tfplan
                '''
            }
        }
        stage('Deploy') {
            steps {
                sh '''
                    cd $DEPLOYMENTS_DIR/$PROJECT_PATH
                    terraform apply -auto-approve tfplan
                '''
            }
        }
        stage('Redeploy Api Gateway to stage') {
            steps {
                sh '''
                    cd $DEPLOYMENTS_DIR/$PROJECT_PATH
                    echo "Exporting Terraform outputs..."
                    REST_API_ID=$(terraform output -raw rest_api_id)
                    DEPLOYMENT_ID=$(terraform output -raw deployment_id)
                    STAGE_NAME=$(terraform output -raw stage_name)
                    DEPLOYMENT_REGION=$(terraform output -raw deployment_region)

                    aws apigateway create-deployment \
                        --rest-api-id $REST_API_ID \
                        --stage-name $STAGE_NAME \
                        --region $DEPLOYMENT_REGION
                '''
            }
        }
    }
}
