pipeline {
    agent any
    stages {
        stage('Terraform Init') {
            steps {
                sh '''
                    terraform --version
                    cd /home/jenkins/agent/aws/storage/efs-ec2-simple
                    ls
                    terraform init
                '''
            }
        }
        stage('Terraform Plan') {
            steps {
                sh '''
                    cd /home/jenkins/agent/aws/storage/efs-ec2-simple
                    terraform plan -out=tfplan
                '''
            }
        }
        stage('Deploy') {
            steps {
                sh '''
                    cd /home/jenkins/agent/aws/storage/efs-ec2-simple
                    terraform apply -auto-approve tfplan
                '''
            }
        }
    }
}
