pipeline {
    agent any
    stages {
        stage('Terraform Init') {
            steps {
                sh '''
                    terraform --version
                    cd /home/jenkins/agent/aws/storage/efs-ec2-simple
                    ls
                    terraform init
                '''
            }
        }
    }
}
